### ISSUE TITLE
Ability to copy and paste

### ISSUE THREAD

**Issue by plaidpants** [whscullin/apple2js#25]
Would be nice to have the ability to paste text into the command line to allow applesoft basic programs to be easily moved into the emulation or to be able to copy the text on the screen out of the emulation.

**Comment by whscullin** [comment]
The last time I investigated this (which was admittedly a while ago), the browser APIs for it were pretty crude. But doing another round of investigation things look better. I've added support that seems to work in major current browsers. For now in the Apple //e emulator you need to use the menu items because hot keys still are intercepted by the browser.

**Comment by plaidpants** [comment]
Thanks I tried it out on some old basic programs of mine and was able to paste them into the emulator and run them. This is really cool.

**Comment by whscullin** [comment]
You're welcome. I find I use this a lot now, too 😄
